// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWklvSUolO2STsRHxdW6AtyhjJcMQb2cA',
    appId: '1:235395250738:web:48f0c69bc8680ebd60da2b',
    messagingSenderId: '235395250738',
    projectId: 'porter-wellness-app',
    authDomain: 'porter-wellness-app.firebaseapp.com',
    databaseURL: 'https://porter-wellness-app-default-rtdb.firebaseio.com',
    storageBucket: 'porter-wellness-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG44SUKEhVDy1i_JSendFGLj3zB19Jyp8',
    appId: '1:235395250738:android:5257b957a8a9b02a60da2b',
    messagingSenderId: '235395250738',
    projectId: 'porter-wellness-app',
    databaseURL: 'https://porter-wellness-app-default-rtdb.firebaseio.com',
    storageBucket: 'porter-wellness-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5l0jnBcfEmivRugYVgNY4s1X-wE9WEcU',
    appId: '1:235395250738:ios:b3037413404455e060da2b',
    messagingSenderId: '235395250738',
    projectId: 'porter-wellness-app',
    databaseURL: 'https://porter-wellness-app-default-rtdb.firebaseio.com',
    storageBucket: 'porter-wellness-app.appspot.com',
    iosClientId: '235395250738-3sn1hmr2i4v9r00jkab7hj60vmfvakkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.porterWellnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5l0jnBcfEmivRugYVgNY4s1X-wE9WEcU',
    appId: '1:235395250738:ios:b3037413404455e060da2b',
    messagingSenderId: '235395250738',
    projectId: 'porter-wellness-app',
    databaseURL: 'https://porter-wellness-app-default-rtdb.firebaseio.com',
    storageBucket: 'porter-wellness-app.appspot.com',
    iosClientId: '235395250738-3sn1hmr2i4v9r00jkab7hj60vmfvakkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.porterWellnessApp',
  );
}
