import '../screens/assessment_screen.dart';

List<AssessmentScreen> assessments = [
  AssessmentScreen(
    pageNum: 1,
    title: 'physical health',
    subTitle:
        'Physical wellness is about adopting healthy habits such as routine medical exams, adequate sleep, a balanced diet, regular exercise, and more.',
    firstButton: false,
    secondButton: false,
    thirdButton: false,
    fourthButton: false,
    fifthButton: false,
    sixthButton: false,
    firstOption: 'Chronic Pain',
    secondOption: 'Chronic Health Concerns',
    thirdOption: 'Weight',
    fourthOption: 'Nutrition',
    fifthOption: 'Limited mobility',
    sixthOption: 'Sedentary Lifestyle',
  ),
  AssessmentScreen(
    pageNum: 2,
    title: 'emotions',
    subTitle:
        'Emotional wellness encompasses optimism, self-esteem, self-acceptance, and the ability to experience and cope with feelings independently and interpersonally.',
    firstButton: false,
    secondButton: false,
    thirdButton: false,
    fourthButton: false,
    fifthButton: false,
    sixthButton: false,
    firstOption: 'Depression',
    secondOption: 'Anger Management',
    thirdOption: 'Trauma',
    fourthOption: 'Grief',
    fifthOption: 'Relationship Issues',
    sixthOption: 'Anxiety',
  ),
  AssessmentScreen(
    pageNum: 3,
    title: 'social health',
    subTitle:
        'Social wellness refers to one\'s ability to interact with people around them. It involves using good communication skills, having meaningful relationships, etc.',
    firstButton: false,
    secondButton: false,
    thirdButton: false,
    fourthButton: false,
    fifthButton: false,
    sixthButton: false,
    firstOption: 'Recent Relocation',
    secondOption: 'Social Anxiety',
    thirdOption: 'Dating/Friendship',
    fourthOption: 'Seeking Community',
    fifthOption: 'Immigrant Adjustment',
    sixthOption: 'Local Meet-ups',
  ),
  AssessmentScreen(
    pageNum: 4,
    title: 'occupational health',
    subTitle:
        'Occupational wellness involves preparing for and participating in work that provides personal satisfaction that is consistent with your values, goals, and lifestyle.',
    firstButton: false,
    secondButton: false,
    thirdButton: false,
    fourthButton: false,
    fifthButton: false,
    sixthButton: false,
    firstOption: 'Career Pivot',
    secondOption: 'Career Counseling',
    thirdOption: 'Resume Guidance',
    fourthOption: 'Recent job loss',
    fifthOption: 'Academic Stress',
    sixthOption: 'Career/Academic Burnout',
  ),
  AssessmentScreen(
    pageNum: 5,
    title: 'spiritual health',
    subTitle:
        'Spiritual wellness involves seeking and having a meaning and purpose in life, as well as participating in activities that are consistent with one\'s beliefs and values.',
    firstButton: false,
    secondButton: false,
    thirdButton: false,
    fourthButton: false,
    fifthButton: false,
    sixthButton: false,
    firstOption: 'Seeking community',
    secondOption: 'Spiritual disconnection',
    thirdOption: 'Spiritual exploration',
    fourthOption: 'Alternative healing (Reiki, Tarot, Crystals)',
    fifthOption: 'Seeking church',
    sixthOption: 'Meditation',
  ),
  AssessmentScreen(
    pageNum: 6,
    title: 'financial health',
    subTitle:
        'Financial wellness includes our relationship with money, skills to manage resources to live within our means, and setting realistic goals.',
    firstButton: false,
    secondButton: false,
    thirdButton: false,
    fourthButton: false,
    fifthButton: false,
    sixthButton: false,
    firstOption: 'Financial Counseling',
    secondOption: 'Life Insurance/Will preparation',
    thirdOption: 'Financial Education',
    fourthOption: 'High debt stress',
    fifthOption: 'Home-ownership',
    sixthOption: 'Investing',
  ),
];
